package view;

import controller.LogTrack;
import java.awt.event.WindowEvent;
import model.CopiaObra;
import model.ObraLiteraria;

public class JFrameCopiaObraCRUD extends javax.swing.JFrame {
    
    private CopiaObra copiaObra;
    private ObraLiteraria obraLiteraria;
    
    private boolean disconnectOnClose;

    public JFrameCopiaObraCRUD(CopiaObra copiaObra, boolean disconnectOnClose) throws Exception {
        initComponents();
        
        setTitle("Cadastro de Cópia de Obra Literária");
        
        if(copiaObra == null) {
            this.copiaObra = new CopiaObra();
        } else {
            this.copiaObra = copiaObra;
            
            if(this.copiaObra.getObraLiteraria() != null){
                this.obraLiteraria = new ObraLiteraria();
                this.obraLiteraria.setCodObraLiteraria(this.copiaObra.getObraLiteraria().getCodObraLiteraria());
                this.obraLiteraria.load();
            }
            
            dataUp();
            jTextFieldID.setEnabled(false);
        }
        
        this.disconnectOnClose = disconnectOnClose;
    }
    
    private void checkInput() throws Exception {
        
        if(jTextFieldID.getText().isEmpty()) {
            throw new Exception("Informe ID.");
        } else {
            if(!jTextFieldID.getText().matches("\\d+")) {
                throw new Exception("O campo ID deve ser um número.");
            }
        }
        
        if(jTextFieldObraLiteraria.getText().isEmpty()) {
            throw new Exception("Selecione uma Obra Literária.");
        }        
    }
    
    private void dataDown() throws Exception {
        copiaObra.setCodCopiaObra(Integer.parseInt(jTextFieldID.getText()));
        
        if(jCheckBoxSituacao.isSelected()) {
            copiaObra.setSituacao("S");
        } else {
            copiaObra.setSituacao("N");
        }
        
        copiaObra.setObraLiteraria(obraLiteraria);
    }
    
    private void dataUp() {
        jTextFieldID.setText(String.valueOf(copiaObra.getCodCopiaObra()));

        if((copiaObra.getSituacao() != null) && (copiaObra.getSituacao().equals("S"))){
            jCheckBoxSituacao.setSelected(true);
        } else {
            jCheckBoxSituacao.setSelected(false);
        }
        
        if(copiaObra.getObraLiteraria().getTitulo() != null) {
            jTextFieldObraLiteraria.setText(copiaObra.getObraLiteraria().getTitulo());
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelID = new javax.swing.JLabel();
        jLabelSituacao = new javax.swing.JLabel();
        jLabelObraLiteraria = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldObraLiteraria = new javax.swing.JTextField();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonSelecionarObra = new javax.swing.JButton();
        jButtonExcluirObra = new javax.swing.JButton();
        jCheckBoxSituacao = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelID.setText("ID");

        jLabelSituacao.setText("Situação");

        jLabelObraLiteraria.setText("Obra Literária");

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonSelecionarObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/search-icon.png"))); // NOI18N
        jButtonSelecionarObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarObraActionPerformed(evt);
            }
        });

        jButtonExcluirObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/eraser-icon.png"))); // NOI18N
        jButtonExcluirObra.setMaximumSize(new java.awt.Dimension(25, 25));
        jButtonExcluirObra.setMinimumSize(new java.awt.Dimension(25, 25));
        jButtonExcluirObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirObraActionPerformed(evt);
            }
        });

        jCheckBoxSituacao.setText("Em empréstimo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldID))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtonExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSalvar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelSituacao)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jCheckBoxSituacao)
                                        .addGap(166, 166, 166))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelObraLiteraria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextFieldObraLiteraria)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addComponent(jButtonSelecionarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonExcluirObra, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelObraLiteraria)
                        .addComponent(jTextFieldObraLiteraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonExcluirObra, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSelecionarObra, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSituacao)
                    .addComponent(jCheckBoxSituacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonSalvar))
                .addGap(8, 8, 8))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecionarObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarObraActionPerformed
        try {
            if(obraLiteraria == null) {
                obraLiteraria = new ObraLiteraria();
            }
            
            JFrameConsultaObraLiteraria jFrameConsulta;
            jFrameConsulta = new JFrameConsultaObraLiteraria(true, false, obraLiteraria);
            
            jFrameConsulta.addWindowListener(new java.awt.event.WindowAdapter(){
                @Override
                public void windowClosed(java.awt.event.WindowEvent evt) {
                    if(obraLiteraria.getTitulo() != null) {
                        jTextFieldObraLiteraria.setText(obraLiteraria.getTitulo());
                    }
                }
            } );
            
            jFrameConsulta.setVisible(true);
        } catch(Exception ex) {
            ex.printStackTrace();
            obraLiteraria = null;
        }
    }//GEN-LAST:event_jButtonSelecionarObraActionPerformed

    private void jButtonExcluirObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirObraActionPerformed
        obraLiteraria = null;
        jTextFieldObraLiteraria.setText(null);
    }//GEN-LAST:event_jButtonExcluirObraActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        System.out.println("Excluir");

        try {
            checkInput();
            dataDown();
            copiaObra.delete();
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        } catch(Exception ex) {
            LogTrack.getInstance().addException(ex, true, this);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        System.out.println("Salvar");

        try {
            checkInput();
            dataDown();
            copiaObra.save();
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        } catch(Exception ex) {            
            LogTrack.getInstance().addException(ex, true, this);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonExcluirObra;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSelecionarObra;
    private javax.swing.JCheckBox jCheckBoxSituacao;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelObraLiteraria;
    private javax.swing.JLabel jLabelSituacao;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldObraLiteraria;
    // End of variables declaration//GEN-END:variables
}
