package view;

import controller.LogTrack;
import java.awt.event.WindowEvent;
import model.ObraLiteraria;
import model.TipoObra;

public class JFrameObraLiterariaCRUD extends javax.swing.JFrame {

    private ObraLiteraria obraLiteraria;
    private TipoObra tipoObra;
    
    private boolean disconnectOnClose;
    
    public JFrameObraLiterariaCRUD(ObraLiteraria obraLiteraria, boolean disconnectOnClose) throws Exception {
        initComponents();
        
        setTitle("Cadastro de Obra Literária");
        
        if(obraLiteraria == null) {
            this.obraLiteraria = new ObraLiteraria();
        } else {
            this.obraLiteraria = obraLiteraria;
            
            if(this.obraLiteraria.getTipoObra() != null) {
                this.tipoObra = new TipoObra();
                this.tipoObra.setCodTipoObra(this.obraLiteraria.getTipoObra().getCodTipoObra());
                this.tipoObra.load();
            }
            
            dataUp();
            jTextFieldID.setEnabled(false);
        }
        
        this.disconnectOnClose = disconnectOnClose;
    }

    private void checkInput() throws Exception {
        
        if(jTextFieldID.getText().isEmpty()) {
            throw new Exception("Informe ID.");
        } else {
            if(!jTextFieldID.getText().matches("\\d+")) {
                throw new Exception("O campo ID deve ser um número.");
            }
        }
        
        
        
    }
    
    private void dataDown() throws Exception {
        obraLiteraria.setCodObraLiteraria(Integer.parseInt(jTextFieldID.getText()));
        obraLiteraria.setTitulo(jTextFieldTitulo.getText());
        obraLiteraria.setAutor(jTextFieldAutor.getText());
        obraLiteraria.setEditora(jTextFieldEditora.getText());
        obraLiteraria.setNroEdicao(jTextFieldEdicao.getText());
        obraLiteraria.setDataPublicacao(jTextFieldDataPublicacao.getText());
        obraLiteraria.setIsbn(jTextFieldISBN.getText());
        obraLiteraria.setQtdPagina(jTextFieldQtdPaginas.getText());
        
        obraLiteraria.setTipoObra(tipoObra);
    }
    
    private void dataUp() {
        jTextFieldID.setText(String.valueOf(obraLiteraria.getCodObraLiteraria()));
        jTextFieldTitulo.setText(obraLiteraria.getTitulo());
        jTextFieldAutor.setText(obraLiteraria.getAutor());
        jTextFieldEditora.setText(obraLiteraria.getEditora());
        jTextFieldEdicao.setText(obraLiteraria.getNroEdicao());
        jTextFieldDataPublicacao.setText(obraLiteraria.getDataPublicacao());
        jTextFieldISBN.setText(obraLiteraria.getIsbn());
        jTextFieldQtdPaginas.setText(obraLiteraria.getQtdPagina());
        
        if(obraLiteraria.getTipoObra().getDescricao() != null) {
            jTextFieldTipoObra.setText(obraLiteraria.getTipoObra().getDescricao());
        }
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabelID = new javax.swing.JLabel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelEditora = new javax.swing.JLabel();
        jLabelAutor = new javax.swing.JLabel();
        jLabelTipoObra = new javax.swing.JLabel();
        jLabelDataPublicacao = new javax.swing.JLabel();
        jLabelQtdPaginas = new javax.swing.JLabel();
        jLabelEdicao = new javax.swing.JLabel();
        jLabelISBN = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldAutor = new javax.swing.JTextField();
        jTextFieldQtdPaginas = new javax.swing.JTextField();
        jTextFieldEdicao = new javax.swing.JTextField();
        jTextFieldEditora = new javax.swing.JTextField();
        jTextFieldISBN = new javax.swing.JTextField();
        jTextFieldDataPublicacao = new javax.swing.JTextField();
        jTextFieldTipoObra = new javax.swing.JTextField();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSelecionarTipoObra = new javax.swing.JButton();
        jButtonApagarTipoObra = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelID.setText("ID");

        jLabelTitulo.setText("Título");

        jLabelEditora.setText("Editora");

        jLabelAutor.setText("Autor");

        jLabelTipoObra.setText("Tipo Obra");

        jLabelDataPublicacao.setText("Data da Publicação");

        jLabelQtdPaginas.setText("Páginas");

        jLabelEdicao.setText("Edição");

        jLabelISBN.setText("ISBN");

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSelecionarTipoObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/search-icon.png"))); // NOI18N
        jButtonSelecionarTipoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelecionarTipoObraActionPerformed(evt);
            }
        });

        jButtonApagarTipoObra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/eraser-icon.png"))); // NOI18N
        jButtonApagarTipoObra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonApagarTipoObraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldID))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelQtdPaginas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldQtdPaginas))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelISBN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldISBN))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelDataPublicacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldDataPublicacao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEdicao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEdicao))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelEditora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldEditora))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAutor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAutor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelTitulo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTitulo))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(78, 238, Short.MAX_VALUE)
                        .addComponent(jButtonExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabelTipoObra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldTipoObra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSelecionarTipoObra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonApagarTipoObra, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelID)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitulo)
                    .addComponent(jTextFieldTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAutor)
                    .addComponent(jTextFieldAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelEditora)
                    .addComponent(jTextFieldEditora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEdicao)
                    .addComponent(jTextFieldEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDataPublicacao)
                    .addComponent(jTextFieldDataPublicacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelISBN)
                    .addComponent(jTextFieldISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelQtdPaginas)
                    .addComponent(jTextFieldQtdPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelTipoObra)
                        .addComponent(jTextFieldTipoObra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonApagarTipoObra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSelecionarTipoObra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonExcluir))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelecionarTipoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelecionarTipoObraActionPerformed
        try {
            if(tipoObra == null) {
                tipoObra = new TipoObra();
            }
            
            JFrameConsultaTipoObra jFrameConsulta;
            jFrameConsulta = new JFrameConsultaTipoObra(true, false, tipoObra);
            
            jFrameConsulta.addWindowListener(new java.awt.event.WindowAdapter(){
                @Override
                public void windowClosed(java.awt.event.WindowEvent evt) {
                    if(tipoObra.getDescricao() != null) {
                        jTextFieldTipoObra.setText(tipoObra.getDescricao());
                    }
                }
            } );
            
            jFrameConsulta.setVisible(true);
        } catch(Exception ex) {
            ex.printStackTrace();
            tipoObra = null;
        }
    }//GEN-LAST:event_jButtonSelecionarTipoObraActionPerformed

    private void jButtonApagarTipoObraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonApagarTipoObraActionPerformed
        tipoObra = null;
        jTextFieldTipoObra.setText(null);
    }//GEN-LAST:event_jButtonApagarTipoObraActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        System.out.println("Excluir");

        try {
            checkInput();
            dataDown();
            obraLiteraria.delete();
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        } catch(Exception ex) {
            LogTrack.getInstance().addException(ex, true, this);
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        System.out.println("Salvar");

        try {
            checkInput();
            dataDown();
            obraLiteraria.save();
            this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        } catch(Exception ex) {            
            LogTrack.getInstance().addException(ex, true, this);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonApagarTipoObra;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonSelecionarTipoObra;
    private javax.swing.JLabel jLabelAutor;
    private javax.swing.JLabel jLabelDataPublicacao;
    private javax.swing.JLabel jLabelEdicao;
    private javax.swing.JLabel jLabelEditora;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelISBN;
    private javax.swing.JLabel jLabelQtdPaginas;
    private javax.swing.JLabel jLabelTipoObra;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldDataPublicacao;
    private javax.swing.JTextField jTextFieldEdicao;
    private javax.swing.JTextField jTextFieldEditora;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldISBN;
    private javax.swing.JTextField jTextFieldQtdPaginas;
    private javax.swing.JTextField jTextFieldTipoObra;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
